tummy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tummyapp.urls', namespace='tummyapp')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tummyapp/urls.py
from django.urls import path
from tummyapp import views


app_name = 'tummyapp'

urlpatterns = [
    path('home/', views.home, name='home'),
    # prurchase
    path('package_orders/', views.package_orders, name='package_orders'),
    path('package_order_form/', views.package_order_form,
         name='package_order_form'),

    path('package_product_purchases/', views.package_product_purchases, name='package_product_purchases'),
    path('package_product_purchases_form/', views.package_product_purchases_form, name='package_product_purchases_form'),
#   
         

    path('product_orders/', views.product_orders, name='product_orders'),
    path('product_orders_form/', views.product_orders_form,
         name='product_orders_form'),

    path('product_purchases/', views.product_purchases, name='product_purchases'),
    path('product_purchases_form/', views.product_purchases_form,
         name='product_purchases_form'),

     path('slider_images/', views.slider_images, name='slider_images'),
     path('slider_images_form/', views.slider_images_form, name='slider_images_form'),
    # -------------------------------------------------------------------------------------------------------------------

    # services
    path('package_products/', views.package_products, name='package_products'),
    path('package_products_form/', views.package_products_form,
         name='package_products_form'),

    path('packages/', views.packages, name='packages'),
    path('packages_form/', views.packages_form, name='packages_form'),

    path('product_categorys/', views.product_categorys, name='product_categorys'),
    path('product_categorys_form/', views.product_categorys_form,
         name='product_categorys_form'),

    path('product_package_price_historys/', views.product_package_price_historys,
         name='product_package_price_historys'),
    path('product_package_price_historys_form/', views.product_package_price_historys_form,
         name='product_package_price_historys_form'),

     path('product_price_historys/', views.product_price_historys,
         name='product_price_historys'),
    path('product_price_historys_form/', views.product_price_historys_form,
         name='product_price_historys_form'),

    path('products/', views.products, name='products'),
    path('products_form/', views.products_form, name='products_form'),
    # --------------------------------------------------------------------------------------------------------------------------
    # useraccount
    path('blog_posts/', views.blog_posts, name='blog_posts'),
    path('blog_posts_form/', views.blog_posts_form, name='blog_posts_form'),

    path('email_otps/', views.email_otps, name='email_otps'),
    path('email_otps_form/', views.email_otps_form, name='email_otps_form'),

    path('profiles/', views.profiles, name='profiles'),
    path('profiles_form/', views.profiles_form, name='profiles_form'),

    path('user_notifications/', views.user_notifications,
         name='user_notifications'),
    path('user_notifications_form/', views.user_notifications_form,
         name='user_notifications_form'),

    path('users/', views.users, name='users'),
    path('users_form/', views.users_form, name='users_form'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'newcss/new.css' %}"/>
    
</head>
<body>
    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock navbar%}


    {% block content %}
    {% endblock content %}
</body>
</html>

templates/navbar.html
<nav class="nav-area">
<ul class="menu" >
<li><a href="{% url 'tummyapp:home' %}">Home</a></li>
<li><a href="#">Purchase</a>
  <ul id="ser">
    <li><a href="{% url 'tummyapp:package_orders' %}">Package order</a>
            <ul>
            <li><a href="{% url 'tummyapp:package_order_form' %}">Add</a></li>
            </ul>
    </li>
    <li><a href="{% url 'tummyapp:package_product_purchases' %}">Package product purchases</a>
            <ul>
            <li><a href="{% url 'tummyapp:package_product_purchases_form' %}">Add</a></li>
            </ul>
    </li>
    <li><a href="{% url 'tummyapp:product_orders' %}">Product orders</a>
            <ul>
            <li><a href="{% url 'tummyapp:product_orders_form' %}">Add</a></li>
            </ul>
    </li>
    <li><a href="{% url 'tummyapp:product_purchases' %}">Product purchases</a>
            <ul>
            <li><a href="{% url 'tummyapp:product_purchases_form' %}">Add</a></li>
            </ul>
    </li>

    <li><a href="{% url 'tummyapp:slider_images' %}">Slider images</a>
            <ul>
            <li><a href="{% url 'tummyapp:slider_images_form' %}">Add</a></li>
            </ul>
    </li>
    
  </ul>


<li><a href="#">Services</a>
  <ul id="ser">
    <li><a href="{% url 'tummyapp:package_products' %}">Package products</a>
            <ul>
            <li><a href="{% url 'tummyapp:package_products_form' %}">Add</a></li>
            </ul>
    </li>
    <li><a href="{% url 'tummyapp:packages' %}">Packages</a>
            <ul>
            <li><a href="{% url 'tummyapp:packages_form' %}">Add</a></li>
            </ul>
    </li>
    <li><a href="{% url 'tummyapp:product_categorys' %}">Product categorys</a>
            <ul>
            <li><a href="{% url 'tummyapp:product_categorys_form' %}">Add</a></li>
            </ul>
    </li>
    <li><a href="{% url 'tummyapp:product_package_price_historys' %}">Product package price historys</a>
            <ul>
            <li><a href="{% url 'tummyapp:product_package_price_historys_form' %}">Add</a></li>
            </ul>
    </li>
    <li><a href="{% url 'tummyapp:product_price_historys' %}">Product price historys</a>
            <ul>
            <li><a href="{% url 'tummyapp:product_price_historys_form' %}">Add</a></li>
            </ul>
    </li>
    <li><a href="{% url 'tummyapp:products' %}">Products</a>
            <ul>
            <li><a href="{% url 'tummyapp:products_form' %}">Add</a></li>
            </ul>
    </li>
  </ul>


<li><a href="#">Useraccount</a>
  <ul id="ser">
    <li><a href="{% url 'tummyapp:blog_posts' %}">Blog posts</a>
            <ul>
            <li><a href="{% url 'tummyapp:blog_posts_form' %}">Add</a></li>
            </ul>
    </li>
    <li><a href="{% url 'tummyapp:email_otps' %}">Email otps </a>
            <ul>
            <li><a href="{% url 'tummyapp:email_otps_form' %}">Add</a></li>
            </ul>
    </li>
    <li><a href="{% url 'tummyapp:profiles' %}">Profiles</a>
            <ul>
            <li><a href="{% url 'tummyapp:profiles_form' %}">Add</a></li>
            </ul>
    </li>
    <li><a href="{% url 'tummyapp:user_notifications' %}">User notifications</a>
            <ul>
            <li><a href="{% url 'tummyapp:user_notifications_form' %}">Add</a></li>
            </ul>
    </li>
    <li><a href="{% url 'tummyapp:users' %}">Users</a>
            <ul>
            <li><a href="{% url 'tummyapp:users_form' %}">Add</a></li>
            </ul>
    </li>
  </ul>
        

</ul>
</nav>